<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="RestService"
     targetNamespace="http://xmlns.oracle.com/TestSOAApplication/CompositeProj/RestService"
     xmlns:tns="http://xmlns.oracle.com/TestSOAApplication/CompositeProj/RestService"
     xmlns:inp1="http://TargetNamespace.com/RestService_getCustomerOperation_request"
     xmlns:inp2="http://TargetNamespace.com/RestService_getCustomerOperation_response"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://TargetNamespace.com/OrderrRestRef_createOrderrEROperation_response"
    >
    <plnk:partnerLinkType name="RestService">
        <plnk:role name="RestServiceProvider" portType="tns:RestService_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/RestService_getCustomerOperation_request"
                 schemaLocation="../Schemas/customer_request.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/RestService_getCustomerOperation_response"
                 schemaLocation="../Schemas/customer_response.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/OrderrRestRef_createOrderrEROperation_response"
                 schemaLocation="../Schemas/orderr_response_er.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="getCustomerOperation_inputMessage">
        <wsdl:part name="request" element="inp1:Root-Element"/>
    </wsdl:message>
    <wsdl:message name="getCustomerOperation_outputMessage">
        <wsdl:part name="reply" element="inp2:Root-Element"/>
    </wsdl:message>
    <wsdl:portType name="RestService_ptt">
        <wsdl:operation name="getCustomerOperation">
            <wsdl:input message="tns:getCustomerOperation_inputMessage"/>
            <wsdl:output message="tns:getCustomerOperation_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
